// react-todomvc/src/components/TodoHeader.js
import React, { Component } from 'react'
class Header extends Component {
  state = {
    name: '',
  }
  render() {
    return (
      <header className="header">
        <h1>todos</h1>
        <input
          className="new-todo"
          placeholder="接下来我们要做什么呢?"
          autoFocus
          value={this.state.name}
          onChange={(e) => this.setState({ name: e.target.value })}
          onKeyUp={this.add}
        />
      </header>
    )
  }
  add = (e) => {
    if (e.keyCode !== 13) return
    if (!this.state.name.trim()) return alert('不能为空')
    this.props.add(this.state.name)
    this.setState({
      name: '',
    })
  }
}
export default Header

// vue-todomvc/src/components/TodoHeader.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <input id="toggle-all" class="toggle-all" type="checkbox" v-model="all" />
    <label for="toggle-all"></label>
    <input
      class="new-todo"
      placeholder="输入任务名称-回车确认"
      autofocus
      v-model="name"
      @keyup="add"
    />
  </header>
</template>

<script>
export default {
  props: ['arr'],
  data() {
    return {
      name: '',
    }
  },
  computed: {
    all: {
      set(checked) {
        this.arr.forEach((element) => {
          element.isDone = checked
        })
      },
      get() {
        return this.arr.length !== 0 && this.arr.every((item) => item.isDone)
      },
    },
  },
  methods: {
    add(e) {
      if (e.keyCode !== 13) return
      if (!this.name.trim()) return alert('请输入')
      this.$emit('headerAdd', this.name)
      this.name = ''
    },
  },
}
</script>
