// react-todomvc/src/components/TodoFooter.js
import React, { Component } from 'react'
class Footer extends Component {
  render() {
    const { list, type } = this.props
    if (list.length === 0) return null
    let leftCount = list.filter((item) => !item.done).length
    let isShow = list.some((item) => item.done)
    return (
      <footer className="footer">
        <span className="todo-count">
          <strong>{leftCount}</strong> item left
        </span>
        <ul className="filters">
          <li>
            <a
              className={type === 'all' ? 'selected' : ''}
              onClick={() => this.chang('all')}
              href="#/"
            >
              All
            </a>
          </li>
          <li>
            <a
              className={type === 'active' ? 'selected' : ''}
              onClick={() => this.chang('active')}
              href="#/active"
            >
              Active
            </a>
          </li>
          <li>
            <a
              className={type === 'completed' ? 'selected' : ''}
              onClick={() => this.chang('completed')}
              href="#/completed"
            >
              Completed
            </a>
          </li>
        </ul>
        {isShow && (
          <button className="clear-completed" onClick={this.del}>
            Clear completed
          </button>
        )}
      </footer>
    )
  }
  del = () => {
    this.props.Del()
  }
  chang(type){
    this.props.changeType(type)
  }
}
export default Footer

// vue-todomvc/src/components/TodoFooter.vue
<template>
  <div>
    <footer class="footer" v-if="arr.length !== 0">
      <span class="todo-count"
        >剩余<strong>{{ count }}未完成</strong></span
      >
      <ul class="filters">
        <li>
          <a
            :class="{ selected: type === 'all' }"
            href="javascript:;"
            @click="change('all')"
            >全部</a
          >
        </li>
        <li>
          <a
            :class="{ selected: type === 'no' }"
            href="javascript:;"
            @click="change('no')"
            >未完成</a
          >
        </li>
        <li>
          <a
            :class="{ selected: type === 'yes' }"
            href="javascript:;"
            @click="change('yes')"
            >已完成</a
          >
        </li>
      </ul>
      <button class="clear-completed" @click="clear()" v-show="this.arr.some(item=> item.isDone)" >清除已完成</button>
    </footer>
  </div>
</template>

<script>
export default {
  props: ['arr', 'type'],
  computed: {
    count() {
      let finish = this.arr.filter((item) => !item.isDone)
      return finish.length
    },
  },
  methods: {
    change(type) {
      this.$emit('footerChange', type)
    },
    clear() {
      this.$emit('footerClear')
    },
  },
}
</script>
